### ISSUE TITLE
UI Error When Turning on MasterMerchant Value Replacement

### ISSUE THREAD

**Issue by bengincley** [prasoc/BetterUI#12]
I consistently get the following UI error only when turning the Inventory - MasterMerchant value replacement setting ON (operating on the latest patch 6/2/16).

_user:/AddOns/BetterUI/Modules/Inventory/InventoryList.lua:186 function expected instead of nil
stack traceback: 
user:/Addons/BetterUI/Modules/Inventory/InventoryList.lua:186: in function 'BUI_Shared_GamepadEntry_OnSetup'
EsoUI/Libraries/ZO_ParametricScrollList/ZO_ParametricScrollList.lua:1029: in function 'ZO_ParametricScrollList:RunSetupOnControl'
...
..._
Any patch or help would be greatly appreciated.

**Comment by prasoc** [comment]
Hi, I will fix this when I get back from work - thanks for posting the stack trace, it's very handy for debugging purposes

**Comment by prasoc** [comment]
Fixed in V2.02, will push updates to the Git page, too
