### ISSUE TITLE
UI Error on resetting Guild Store filters

### ISSUE THREAD

**Issue by lawsongrey** [prasoc/BetterUI#17]
When resetting filters while in guild store, this error appears

user:/AddOns/BetterUI/Modules/GuildStore/Module.lua:108: function expected instead of nil
stack traceback:
	user:/AddOns/BetterUI/Modules/GuildStore/Module.lua:108: in function 'callback'
	EsoUI/Libraries/ZO_KeybindStrip/ZO_KeybindStrip.lua:614: in function 'ZO_KeybindStrip:TryHandlingKeybindDown'
	(tail call): ?
	(tail call): ?

**Comment by prasoc** [comment]
I will look into this. Thanks for reporting it!

**Comment by prasoc** [comment]
Fixed in V2.25 (uploading shortly)
